Repository tigera/key-cert-provisioner, pull requests merged in 2021-04, with the labels that each got.

#16 Update go build to 0.51, remove duplicate targets
  Makefile
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#17 [PICK] Update go build to 0.51, remove duplicate targets
  Makefile
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#15 use certificate v1 for 1.19 onward and v1beta1 for older versions for…
  pkg/k8s/certificate.go
  pkg/k8s/certificate_test.go
Labels: docs-pr-required, hold-merge, release-note-required

#18 Write the CA cert to a file if this information is present in the environment variables
  pkg/cfg/config.go
  pkg/k8s/certificate.go
  pkg/k8s/certificate_test.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#19 add organization env, add semv2 id
  Makefile
Labels: docs-not-required, release-note-not-required
