Repository tigera/key-cert-provisioner, pull requests merged in 2022-01, with the labels that each got.

#29 Update to use v065 build container
  Makefile
  signer/main.go
Labels: docs-pr-required, release-note-required

#28 Update to use v065 build container
  Makefile
  signer/main.go
Labels: docs-pr-required, release-note-required

#30 update k8s api version
  signer/main.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#32 Update gomod version, and crypto and net libraries
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#31 Update gomod version, and crypto and net libraries
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#33 Set condition for v1 api to true
  signer/main.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#34 [EV-1564] add squash to builds
  .gitignore
  .semaphore/semaphore.yml
  Makefile
Labels: docs-pr-required, release-note-required
